using DevLife.Enums;
using System.ComponentModel.DataAnnotations;

namespace DevLife.Models.MeetingExcuse;

public class MeetingExcuseStats
{
    public int Id { get; set; }

    [Required]
    public int UserId { get; set; }

    /// <summary>
    /// Total excuses generated by this user
    /// </summary>
    public int TotalExcusesGenerated { get; set; } = 0;

    /// <summary>
    /// Total excuses marked as favorites
    /// </summary>
    public int TotalFavorites { get; set; } = 0;

    /// <summary>
    /// Most frequently used category
    /// </summary>
    public MeetingCategory? FavoriteCategory { get; set; }

    /// <summary>
    /// Most frequently used excuse type
    /// </summary>
    public ExcuseType? FavoriteType { get; set; }

    /// <summary>
    /// Average believability score of used excuses
    /// </summary>
    public double AverageBelievability { get; set; } = 0.0;

    /// <summary>
    /// JSON array of recent excuse IDs for streak tracking
    /// </summary>
    [StringLength(2000)]
    public string RecentExcusesJson { get; set; } = "[]";

    /// <summary>
    /// Current streak of days using the excuse generator
    /// </summary>
    public int CurrentStreak { get; set; } = 0;

    /// <summary>
    /// Longest streak achieved
    /// </summary>
    public int LongestStreak { get; set; } = 0;

    /// <summary>
    /// JSON array of unlocked achievements
    /// </summary>
    [StringLength(2000)]
    public string UnlockedAchievementsJson { get; set; } = "[]";

    public DateTime LastExcuseGenerated { get; set; } = DateTime.UtcNow;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // Navigation property
    public User User { get; set; } = null!;
}
